import type { Metadata } from "next";
import { Header, Main, Sidebar } from "@/components";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function UserLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main className="main">
          <Sidebar />
          <Main>{children}</Main>
        </main>
      </body>
    </html>
  );
}
